
<MyLayout>
    BoxLayout:
        orientation:"vertical"
        size:root.width,root.height

        Label:
            id:name_label
            text: "what is your name:"
            font_size:60
        TextInput:
            id:name_input
            font_size:50
            multiline:False
            size_hint:(1,0.5)
        Button:
            size_hint:(1,0.5)
            text:"submit"
            on_press:root.press()
